# Generated by Django 2.0.7 on 2019-08-30 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='adderss',
            new_name='address',
        ),
    ]
